//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIT420Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public Nullable<System.DateTime> GameDateReleased { get; set; }
        public Nullable<int> GameMetacriticScore { get; set; }
        public Nullable<decimal> GamePrice { get; set; }
        public string GameDescription { get; set; }
        public string GameImageHeader { get; set; }
        public string GameImageBackground { get; set; }
        public string GameWebsite { get; set; }
        public Nullable<int> GameSalesNorthAmerica { get; set; }
        public Nullable<int> GameSalesEurope { get; set; }
        public Nullable<int> GameSalesJapan { get; set; }
        public Nullable<int> GameSalesOther { get; set; }
        public Nullable<int> RatingID { get; set; }
        public int GenreID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public int PlatformID { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
